# Generated by Django 2.2.7 on 2019-11-21 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('max', models.IntegerField()),
                ('proj', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('Chour', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='has',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageclass.Classroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageclass.Course')),
            ],
        ),
    ]
