# Generated by Django 2.2.7 on 2019-11-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageclass', '0003_auto_20191124_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='has',
            name='a',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='has',
            name='b',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='has',
            name='c',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='has',
            name='d',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='has',
            name='e',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='has',
            name='f',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='has',
            name='g',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='has',
            name='h',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='has',
            name='l',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='has',
            name='m',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='has',
            name='n',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='has',
            name='w',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
